### ISSUE TITLE
No playback with AMD GPUs

### ISSUE THREAD

**Issue by jannuary** [zelikos/davincibox#74]
**Describe the bug**

Resolve Studio installs successfully, launches, but refuses to playback any media imported or created within the editor, with the playback head getting stuck.

With rusticl, the behavior is similar – but with an actual error message:
![Screenshot from 2024-06-05 11-15-25](https://github.com/zelikos/davincibox/assets/27908024/0e1c9ac3-be53-4e1a-bdd4-41539d865586)

**Installation method used**

- [x] `setup.sh`
- Manual
  - [ ] Distrobox
  - [ ] Toolbox

**To Reproduce**

1. Install and open Davinci Resolve Studio
2. Drag a clip in the timeline, or create a title
3. Try to playback the timeline

**Expected behavior**

Video playing back and appearing in the preview pane.

**System information (please complete the following)**

 - Distro: Fedora Workstation 40
 - Desktop Environment: GNOME 46 Wayland
 - GPU: AMD Radeon RX 560 (2 GB)
 - Version: Studio 19 β2, Studio 17.4.2

**Comment by ItsRogueRen** [comment]
I'm having the same GPU error on my RX 7700XT with the free version of Resolve. My error is almost exactly the same except the error code is -1 instead of -57

My install was also done with the setup.sh file for Resolve 18.6.5, using KDE Plasma (Wayland) on Nobara 40 (Fedora based).

Is this something we will have to wait for Black Magic to fix?

**Comment by zelikos** [comment]
Moreso we're waiting on driver updates than DaVinci Resolve updates

error code -1 is happening on ROCm (AMD's official compute stack, currently the default for AMD GPUs with davincibox)

error -57 happens with Mesa's rusticl (Mesa's OpenCL, opt-in experimental option), but until recently (2-3 weeks ago) it was working fine for me, so maybe with Mesa 24.1 rusticl will be working again?

**Comment by zelikos** [comment]
ROCm is still borked, but as of Mesa 24.1.1, rusticl seems to be working with Resolve again. 

![Screenshot from 2024-06-15 22-30-37](https://github.com/zelikos/davincibox/assets/26857149/3969b1a2-c5e2-4776-bce1-ad3f1d773401)

Testing instructions can be found [here in the README](https://github.com/zelikos/davincibox/?tab=readme-ov-file#amd)

**Comment by zelikos** [comment]
As of #89, rusticl is now the default for AMD GPUs instead of ROCm, since the latter has been a frequent source of problems and even relatively newer AMD GPUs (like the RX 6000 series) aren't officially supported by ROCm.

Since rusticl is the default now, simply [update davincibox](https://github.com/zelikos/davincibox#upgrading) and retest for this issue, no special steps required.

**Comment by zelikos** [comment]
Closing this as the switch to rusticl seems to have resolved it, but I'm on an RX 6000 series card and not RX 500, so feel free to reopen if the issue persits @jannuary
